language: elixir
cache: false
matrix:
  include:
    - elixir: 1.10.3
      otp_release: 22.0.2
      services:
        - postgresql
      before_install:
        - gem install fakes3
        - psql -c "CREATE USER nexpo PASSWORD 'nexpo' CREATEDB;"
        - wget https://github.com/phoenixframework/archives/raw/master/phoenix_new.ez
      install:
        - mix local.rebar --force
        - mix local.hex --force
        - mix archive.install --force ./phoenix_new.ez
        - rm ./phoenix_new.ez
        - mix deps.get
        - mix ecto.setup
        - mix run priv/repo/seeds.exs
      script:
        - fakes3 -r $HOME/.s3bucket -p 4567 --license 9806002125 &
        - MIX_ENV=test mix do compile, test --trace
