language: elixir
cache: false
matrix:
  include:
    - elixir: 1.10.3
      otp_release: 22.0
      before_install:
        - gem install fakes3
        - fakes3 -r $HOME/.s3bucket -p 4567 --license 9806002125 &
      install:
        - mix local.rebar --force
        - mix local.hex --force
        - mix deps.get
      script:
        - npm run test-coverage-backend
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      after_script:
        - kill $(pgrep -f fakes3)
