version: '3'
volumes:
  db_data: null
services:
  db:
    image: 'postgres:10.10'
    volumes:
      - 'db_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=nexpo
      - POSTGRES_USER=nexpo
  app:
    build: .
    depends_on:
      - db
    ports:
      - '4000:4000'
