name: Elixir CI

on:
  push:
  pull_request:
    branches: [ $default-branch ]

jobs:
  test:
    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: nexpo
          POSTGRES_PASSWORD: nexpo
          POSTGRES_DB: nexpo
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Elixir
      uses: erlef/setup-elixir@885971a72ed1f9240973bd92ab57af8c1aa68f24
      with:
        elixir-version: '1.10.3'
        otp-version: '22.3'

    - name: Set up NPM
      uses: actions/setup-node@v2

    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: npm run setup

    - name: Run tests
      run: npm test
