name: GitHub Pages

# Publish new docs on merged PR into master branch
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        
      - name: Install dependencies
        run: npm ci
        
      - name: Build docs
        run: npm run generate-docs

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs
